CREATE TABLE IF NOT EXISTS guild (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS post (
  id INTEGER PRIMARY KEY,
  guild_id INTEGER NOT NULL,
  author TEXT NOT NULL,
  content TEXT NOT NULL,
  FOREIGN KEY (guild_id) REFERENCES guild(id)
)
